### ISSUE TITLE
I can't build a binary

### ISSUE THREAD

**Issue by ghost** [dhogborg/rtl-gopow#1]
I suspect that I am making a silly mistake, any idea what I am doing wrong ?
bert@bananapi:~/src/rtl-gopow$ go build
gopow.go:9:2: cannot find package "github.com/dhogborg/rtl-gopow/internal/gopow" in any of:
        /usr/lib/go/src/pkg/github.com/dhogborg/rtl-gopow/internal/gopow (from $GOROOT)
        /home/bert/go/src/github.com/dhogborg/rtl-gopow/internal/gopow (from $GOPATH)
bert@bananapi:~/src/rtl-gopow$ go get github.com/dhogborg/rtl-gopow/internal/gopow
package github.com/dhogborg/rtl-gopow/internal/gopow
        imports github.com/dhogborg/rtl-gopow/internal/resources
        imports github.com/dhogborg/rtl-gopow/internal/resources
        imports github.com/dhogborg/rtl-gopow/internal/resources: cannot find package "github.com/dhogborg/rtl-gopow/internal/resources" in any of:
        /usr/lib/go/src/pkg/github.com/dhogborg/rtl-gopow/internal/resources (from $GOROOT)
        /home/bert/go/src/github.com/dhogborg/rtl-gopow/internal/resources (from $GOPATH)
bert@bananapi:~/src/rtl-gopow$ go version
go version go1.3.3 linux/arm
bert@bananapi:~/src/rtl-gopow$ 

I previously setup my environment with the following commands:
$ sudo apt-get -y install golang
$ export GOROOT=/usr/lib/go
$ export GOPATH=$HOME/go

$ go get github.com/Sirupsen/logrus
$ go get code.google.com/p/freetype-go/freetype
$ go get github.com/dustin/go-humanize
$ go get github.com/lucasb-eyer/go-colorful
$ go get github.com/codegangsta/cli

So new to go, as you might have guessed.

**Comment by dhogborg** [comment]
You set your GOPATH to `~/go/`, so rtl-gopow should be cloned in `~/go/src/github.com/dhogborg/rtl-gopow`. When cloned you can run `go get ./...` in rtl-gopow/ to download deps (you did that manually it seems, so that might not be necessary).

Also needed for building is the tool go-bindata (https://github.com/jteeuwen/go-bindata). Install that with `go get -u github.com/jteeuwen/go-bindata/...`. Make sure `~/go/bin` is in your path so your shell can run the go-bindata command.

Then build rtl-gopow with `make build_platform` where platform is the target platform you want to compile the binary for. Can be one of:
- build_darwin
- build_linux
- build_arm5
- build_arm7
- build_windows

A `make` command without parameters will build a darwin binary.
Look in the Makefile for more info.

If you want to run with `go run *.go` you will need to run `make resources` first. That only has to be done once, or when changing contents of the resource/ folder.

**Comment by ghost** [comment]
Thank you, that fixed it. The only problem I had then was not enough RAM to compile it. 800MiB RAM free was not enough, which actually surprised me.

bert@bananapi:~/go/src/github.com/dhogborg$ export PATH=$PATH:~/go/bin
bert@bananapi:~/go/src/github.com/dhogborg$ make resources
go-bindata -pkg resources -o internal/resources/resources.go resources/...
bert@bananapi:~/go/src/github.com/dhogborg$ go get -u github.com/jteeuwen/go-bindata/...
bert@bananapi:~/go/src/github.com/dhogborg$ make build_arm7
GOOS=linux GOARM=7 GOARCH=arm go build -a -o ./build/gopow _.go
go build github.com/dhogborg/rtl-gopow/internal/resources: signal: killed
Makefile:28: recipe for target 'build_arm7' failed
make: *_\* [build_arm7] Error 1
bert@bananapi:~/go/src/github.com/dhogborg$

And a quick dmesg showed this:
[  175.888338] lowmemorykiller: Killing '5g' (622), adj 0,
[  175.888347]    to free 835120kB on behalf of '5g' (622) because
[  175.888352]    cache 5812kB is below limit 6144kB for oom_score_adj 0
[  175.888357]    Free memory is -2432kB above reserved

I killed everything that I could to free up as much RAM as possible and it was still not enough. So I added 1GiB extra swap (800MiB RAM+512MiB swap+1GiB swap) and temporarily disabled low free memory process killing 
sudo dd if=/dev/zero of=/swapfile2 bs=1024 count=1048576
sudo chown root:root /swapfile2
sudo chmod 0600 /swapfile2
sudo mkswap /swapfile2
sudo swapon /swapfile2
sudo sysctl vm.overcommit_memory=2

bert@bananapi:~/go/src/github.com/dhogborg/rtl-gopow$ make build_arm7
go-bindata -pkg resources -o internal/resources/resources.go resources/...
GOOS=linux GOARM=7 GOARCH=arm go build -a -o ./build/gopow *.go
**zip ./build/gopow_linux_arm7.zip ./build/gopow**
  **adding: build/gopow (deflated 63%)**
bert@bananapi:~/go/src/github.com/dhogborg/rtl-gopow$ 

sudo sysctl vm.overcommit_memory=0
sudo swapoff /swapfile2
sudo rm /swapfile2
